/**
 * Drizzle schema barrel — generated by `pnpm db:pull` (introspection of the live
 * Postgres), NOT hand-authored. The schema owner is the standalone SQL in
 * `apps/api/db/standalone/`; CI diffs a fresh pull against these files to catch drift.
 *
 * Regenerate: `pnpm db:pull`. Hand-finishing (composite PKs, CHECK→TS unions,
 * stripping GIN/GIST/EXCLUDE index DDL) happens on top of the generated output.
 */
export * from './schema'
export * from './relations'
